version: '3.9'

services:
  nest-app:
    image: nest-app
    # restart: always
    replicas: 2
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3500:3500
