version: '3.9'

services:
  nest-app:
    image: nest-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

  reverse-proxy:
    image: "docker.io/caddy:2-alpine"
    ports:
      - "127.0.0.1:3500:80"
    volumes:
      - "./reverse-proxy.Caddyfile:/etc/caddy/Caddyfile"