apiVersion: apps/v1
# ở đây phiên bản cũ hơn của kubernetes có dạng extensions/v1beta1
kind: Deployment
# kind là loại Deployment
metadata:
  name: kuma-uptime
spec:
  replicas: 2
  # replica ở đây sẽ tạo ra 2 pods luôn luôn chạy, khi một số pods bị down hay chết hay bất kì lý do nào đó sẽ tự động tạo lại số lượng pods bằng 2
  selector:
    matchLabels:
      app: kuma-uptime
  template:
    metadata:
      labels:
        app: kuma-uptime
    spec:
      containers:
      - name: kuma-uptime
      # image của container docker
        image: louislam/uptime-kuma
        ports:
        # port bên trong container
        - containerPort: 3001
---
apiVersion: v1
# kind là loại Service
kind: Service
metadata:
  name: uptime-kuma-svc-2
spec:
  ports:
  # port bên ngoài của pods mà các pods có thể giao tiếp được với nhau
  - port: 80
  # port target với 3001 của deployment
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
  # dựa theo app : kuma-uptime ở labels trên kia sẽ map với service này
    app: kuma-uptime
  type: ClusterIP
