name: Check health server every 60 minutes

on:
  schedule:
    - cron: '0 */1 * * *' # Runs every 60 minutes\

permissions:
  contents: 'write'
  packages: 'write'

jobs:
  check_server_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Check backend prod
        run: curl -m 5 https://api.quayso-mayman.vn/api/v1

      - name: Archive Test Results
        if: failure()
        uses: teknatha136/actions-google-chat-text-message@main
        with:
          google-chat-webhook: 'https://chat.googleapis.com/v1/spaces/AAAAXe1MFzc/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=K3vaz3i9cfSop0tIMJBtWFVZFrfGr55Hsys0fwLfbck'
          text-message: 😭 Your server PROD have problem

  check_server_stage:
    runs-on: ubuntu-latest

    steps:
      - name: Check backend stage
        run: curl -m 5 https://aastage-be.quayso-mayman.vn/api/v1

      - name: Archive Test Results
        if: failure()
        uses: teknatha136/actions-google-chat-text-message@main
        with:
          google-chat-webhook: 'https://chat.googleapis.com/v1/spaces/AAAAXe1MFzc/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=K3vaz3i9cfSop0tIMJBtWFVZFrfGr55Hsys0fwLfbck'
          text-message: 😠 Your server STAGE have problem
    
