name: Check health server

on:
  push:
    branches: ["main"]

jobs:
  ping_server:
    runs-on: ubuntu-latest

    steps:
      - name: Check backend prod
        run: curl -m 5 https://api.quayso-mayman.vn/api/v1

      - name: Check backend stage
        run: curl -m 5 https://stage-be.quayso-mayman.vn/api/v1

      - name: Archive Test Results
        if: failure()
        run: echo "Send notification to google chat"
