name: Check health server

on:
  push:
    branches: ["**"]


permissions:
  contents: 'write'
  packages: 'write'

jobs:
  ping_server:
    runs-on: ubuntu-latest

    steps:
      - name: Check backend prod
        run: curl -m 5 https://api.quayso-mayman.vn/api/v1

      - name: Check backend stage
        run: curl -m 5 https://aastage-be.quayso-mayman.vn/api/v1

      - name: Archive Test Results
        if: failure()
        uses: teknatha136/actions-google-chat-text-message@main
        with:
          google-chat-webhook: 'https://chat.googleapis.com/v1/spaces/AAAAXe1MFzc/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=K3vaz3i9cfSop0tIMJBtWFVZFrfGr55Hsys0fwLfbck'
          text-message: Hello,\nThis is a test message.\nMessage sent by ${{ github.actor }}
