name: 1. Setup Server

on:
  workflow_dispatch:

jobs:
  install-platform:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server and install software
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGE_SERVER_HOST }}
          username: ${{ secrets.STAGE_SERVER_USERNAME }}
          port: 22
          password: ${{ secrets.STAGE_SERVER_PASSWORD}}
          script: |
            # Check if Docker is installed
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing Docker..."
              curl -fsSL https://get.docker.com/ | sudo sh
              sudo usermod -aG docker $USER
              echo "Docker installed. You may need to log out and log back in for group changes to take effect."
              # Note: Changes to user groups won't take effect until next login
              # For this run, we'll use sudo for docker commands
            else
              echo "Docker is already installed"
            fi

            # Check if Docker Compose is already installed
            if ! command -v docker-compose &> /dev/null
            then
              echo "Docker Compose not found, installing..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            else
              echo "Docker Compose is already installed."
            fi

            # Check if Swarm is initialized

            if ! docker info | grep -q "Swarm: active"; then
              echo "Swarm not initialized. Initializing now..."
              sudo docker swarm init
            else
              echo "Swarm is already active"
            fi

            # Check if Nginx Proxy Manager is already installed
            if [ -d "/nginx-proxy-manager" ]; then
              echo "Nginx Proxy Manager is already installed."
            else
              echo "Nginx Proxy Manager not found, installing..."
              mkdir ~/nginx-proxy-manager && cd ~/nginx-proxy-manager

            docker run -d \
              --name nginx-proxy-manager \
              --restart unless-stopped \
              -p 80:80 \
              -p 81:81 \
              -p 443:443 \
              -v $(pwd)/data:/data \
              -v $(pwd)/letsencrypt:/etc/letsencrypt \
              jc21/nginx-proxy-manager:latest

              echo "Docker Compose file created."

              # Start the Nginx Proxy Manager
              docker-compose up -d
              echo "Nginx Proxy Manager is now running."
            fi

            echo "Reboot server to make docker can run without need root"
            sudo reboot